version: "2.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
    networks:
          - kafka
  kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        ports:
          - 9092:9092  
        depends_on:
         - zookeeper 
        environment:
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_BROKER_ID: 1
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
        networks:
          - kafka

  kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
         - "8090:8080"
      depends_on:
       - kafka
      environment:
        DYNAMIC_CONFIG_ENABLE: 'true'         
        KAFKA_CLUSTER_0_NAME: local
        KAFKA_CLUSTER_0_BOOTSTRAPSERVERS: kafka:9092
        KAFKA_CLUSTER_0_ZOOKEEPER: zookeeper:2182 
      networks:
          - kafka

networks:
  kafka:
    driver: bridge

     
        

